### ISSUE TITLE
RShiny Dipwell data - choose site dropdown not matching data

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#53]
The RShiny 'choose site(s)' dropdown does not match uploaded data.  Maybe a caching issue?

@sacrevert

![dip](https://user-images.githubusercontent.com/2699478/98093062-5de68380-1e7f-11eb-9d52-fa5393a36e53.png)

**Comment by sacrevert** [comment]
This is because the site list in the app is uploaded as a static list, and I couldn't work out from the app files what the full list of site/dipwell names looked like (despite my #45). Also, @LaurenceJonesES has said that the download does not contain the most optimal set of information (in terms of separating out site and dipwell name information), so I need a complete set of terms for the relevant fields before this is changed. (Or I could change it so that whatever names are uploaded are picked up, although this is a bit more complicated than providing a static list of expected values)

**Comment by sacrevert** [comment]
@DavidRoy Probably best to close this, as it will change based on amendments to the downloads anyway

**Comment by sacrevert** [comment]
@DavidRoy This can be closed now, as the new interface works from a full, static list of sites provided with the Shiny app.
