### ISSUE TITLE
Plant quadrat recording -- website downloads

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/dunes-app#60]
**For the child download:**
Can we separate out the Site name, the Fixed point location name, and the Group name please [example](https://dunescapes.brc.ac.uk/sites/setup/fixed-point-edit?location_id=248043&dynamic-parent_id=247268)

**For the occurrences download:**
Can we add the Site name, the Group name, and rename the Fixed point location name field from "Location" to "Fixed point location"

Thanks @johnvanbreda 
cc @LaurenceJonesES

**Comment by johnvanbreda** [comment]
@sacrevert I've done the child download. For the occurrences download, the site name has been added and the fixed point column renamed. However because this is based on the Elasticsearch occurrences download the group name, which is a location attribute, is not available. If this is important we will need to consider changing the download to PostgreSQL which is slower but allows any attribute to be included in queries across the database. Or, we could update the Elasticsearch index to include location attributes but that's probably a decision which needs wider discussion.

**Comment by sacrevert** [comment]
@johnvanbreda Many thanks John. I think ultimately we do need the group name, but I'll let you and @DavidRoy decide on methods and priorities. I'm not sure speed is that important in this instance, but, as you say, it may be more efficient in the broader context to update the ES indexing.

**Comment by DavidRoy** [comment]
@johnvanbreda for now I think we can switch to PostgresSQL to allow Oli to progress

Longer term - we'll need the location attributes in the ElasticSearch index as this will be a wider requirement.  

@sacrevert presumably the plant portal will want to query on plot groups?

**Comment by sacrevert** [comment]
Sounds good. Regarding Plant Portal, this is true, but I personally can't say whether the PP stuff has been implemented in exactly the same way as with Dunescapes, and thus whether exactly the same ES solution would apply. Andy would need to comment on this when the time comes.

**Comment by johnvanbreda** [comment]
I'll convert the report. I note that Plant Portal has location attributes such as "Plant portal plot group identifier name text" and "Plant portal plot group identifier name lookup" which makes me suspect the solution will be similar.

**Comment by johnvanbreda** [comment]
I've added an extra button for the PostgreSQL version of the occurrences report.
